name: Run tests

on:
  # run on push in master or rel_* branches excluding changes are only on doc or example folders
  push:
    branches:
      - master
      - "rel_*"
      # branches used to test the workflow
      - "workflow_test_*"
    paths-ignore:
      - "doc/**"
      - "examples/**"

env:
  # global env to all steps
  TOX_WORKERS: -n2

jobs:
  test_docker:
    name: Testing arm64-python${{ matrix.python-version }}-${{ matrix.build-type }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
        build-type:
          - "cext"
          - "nocext"
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - uses: docker://multiarch/ubuntu-core:arm64-bionic
      with:
        args: 'bash .github/scripts/arm64_test.sh python${{ matrix.python-version }} github-${{ matrix.build-type }}'
    - run: |
        ls /home/runner/work/sqlalchemy/sqlalchemy 
