name: Run tests

on:
  # run on push in master or rel_* branches excluding changes are only on doc or example folders
  push:
    branches:
      - master
      - "rel_*"
      # branches used to test the workflow
      - "workflow_test_*"
    paths-ignore:
      - "doc/**"
      - "examples/**"

env:
  # global env to all steps
  TOX_WORKERS: -n2

jobs:
 
  test_docker:
    name: Testing arm64 docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset

    - uses: docker://multiarch/ubuntu-core:arm64-bionic
      with:
        args: 'bash -c "apt-get update && apt-get install -y coreutils curl unzip python3 python3-pip python3.7 libpython3.7-dev git && python3.7 -m pip install --upgrade pip && python3.7 -m pip install --upgrade tox setuptools cibuildwheel wheel auditwheel && python3.7 -m pip install cibuildwheel && python3.7 -m pip list && python3.7 -m cibuidwheel  --plat-name=manylinux2014_aarch64 -d . && auditwheel show *.whl && auditwheel repair *.whl -w . && tox -e github-nocext -q && ls '
    - run: |
        ls /home/runner/work/sqlalchemy/sqlalchemy 
